# Generated by Django 4.1.2 on 2022-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя сотрудника",
                        max_length=100,
                        verbose_name="Имя сотрудника",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию сотрудника",
                        max_length=100,
                        verbose_name="Фамилия сотрудника",
                    ),
                ),
            ],
        ),
    ]
