# Generated by Django 4.1.2 on 2022-10-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mycleaningapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес дома",
                        max_length=100,
                        verbose_name="Адрес дома",
                    ),
                ),
                (
                    "number_of_floors",
                    models.IntegerField(
                        help_text="Введите этажность дома",
                        verbose_name="Этажность дома",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        help_text="Введите состояние дежурства",
                        verbose_name="Состояние дежурства",
                    ),
                ),
                (
                    "date_of_duty",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату дежурства",
                        null=True,
                        verbose_name="Дaтa дежурства",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        help_text=" Выберите сотрудника для дежурства",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mycleaningapp.employee",
                        verbose_name="Сотрудник для дежурства",
                    ),
                ),
                (
                    "home_id",
                    models.ForeignKey(
                        help_text=" Выберите дом для дежурства",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mycleaningapp.home",
                        verbose_name="Дом для дежурства",
                    ),
                ),
            ],
        ),
    ]
